## Constant tensors
1. Ones
2. Zeros

In [2]:
import tensorflow as tf
x = tf.ones(shape = (2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [4]:
x = tf.zeros(shape=(2, 1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

## Random Tensor


In [6]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.) 
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.05857303],
       [0.03547766],
       [0.3366108 ]], dtype=float32)>

In [8]:
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.10727525],
       [0.39657366],
       [0.27820206]], dtype=float32)>

## Variable tensor

In [12]:
# Create a variable tensor with a random value
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))

# Print the current value of the variable
print(v)

# Assign a new value to the variable
v.assign(tf.ones((3, 1)))

# Print the updated value of the variable
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 2.4776085e-04],
       [ 4.2408025e-01],
       [-4.1719782e-01]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


**Now we have seen that constant and variable are different in tensorflow, can cannot be modified and other can be modified.**