## Tensor Element wise operatios
In TensorFlow, element-wise operations are performed using the same syntax as in NumPy. TensorFlow supports all of the standard element-wise operations such as addition, subtraction, multiplication, and division, as well as many other operations that can be used in building neural networks.

For example, to add two tensors element-wise in TensorFlow, you can use the tf.add function:


In [3]:
import numpy as np
import tensorflow as tf

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

c = tf.add(a, b)

print(c)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)


Similarly, you can perform other element-wise operations such as multiplication using `tf.multiply`, subtraction using `tf.subtract`, and division using `tf.divide`.

In addition to the basic element-wise operations, TensorFlow provides a wide range of mathematical functions that can be applied element-wise, such as the `tf.math.sigmoid` and `tf.math.relu` functions. These functions can be used to create custom activation functions for use in neural networks.

## Tensor Reshaping
Reshaping a tensor means rearanging its rows and columns to match a target shape. other words, tensor reshaping allows you to rearrange the dimensions of a tensor without changing the underlying data.

We use tensor reshaping in deep learning when we need to modify the shape of tensors to suit the requirements of different layers of neural networks or different tasks.

For example, in image classification tasks, we often use convolutional neural networks (CNNs), which expect input data to have a specific shape, such as (batch_size, height, width, channels). If the input images do not have this shape, we can reshape them using tensor reshaping to match the required input shape.

Tensor reshaping can also be used to flatten tensors, which is useful when we want to feed a multi-dimensional tensor as input to a dense layer. In this case, we reshape the tensor to have a shape of (batch_size, num_features), where num_features is the total number of elements in the tensor.

In [6]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])

x.shape

(3, 2)

In [8]:
x = x.reshape((6, 1))
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [9]:
x = x.reshape((2, 3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

A special case of reshaping that’s commonly encountered is transposition. Transposing a
matrix means exchanging its rows and its columns

In [11]:
x = np.zeros((300, 20))
x.shape

(300, 20)

In [12]:
x = np.transpose(x)
x.shape

(20, 300)

___